version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: ${POSTGRES_CONTAINER_NAME}
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: ${REDIS_CONTAINER_NAME}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  accuknox-server-task-by-faheem:  
    build: .
    container_name: ${ACCUINOX_SERVER}
    ports:
      - "8080:8080" 
    environment:
        POSTGRES_HOST: ${POSTGRES_CONTAINER_NAME}
        REDIS_HOST: ${REDIS_CONTAINER_NAME}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - postgres
      - redis   
    volumes:
      - .:/app  

volumes:
  postgres_data:
  redis_data:
