version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: accuknox
      POSTGRES_USER: faheem
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
